name: Auto Assign to the nRF Asset Tracker project

on:
  issues:
    types: opened
  pull_request:
    types: opened
env:
  MY_GITHUB_TOKEN: ${{ secrets.AUTO_ASSIGN_ISSUE_TOKEN }}

jobs:
  assign_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Assign new issues and new pull requests to the project
        uses: srggrs/assign-one-project-github-action@1.2.0
        with:
          project: "https://github.com/orgs/NordicSemiconductor/projects/2"
          column_name: "Doing"
