name: Add PRs to nRF Asset Tracker PR dashboard

on:
  pull_request:
    types: opened
env:
  MY_GITHUB_TOKEN: ${{ secrets.AUTO_ASSIGN_ISSUE_TOKEN }}

jobs:
  assign_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Assign new pull requests to the Doing column of the project
        uses: srggrs/assign-one-project-github-action@1.3.1
        if: github.event_name == 'pull_request'
        with:
          project: "https://github.com/orgs/NordicSemiconductor/projects/2"
          column_name: "Doing"
