name: Add PRs to the nRF Asset Tracker Development project

on:
  pull_request:
    types: opened

jobs:
  assign_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Add to project
        uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/NordicSemiconductor/projects/3
          github-token: ${{ secrets.AUTO_ASSIGN_ISSUE_TOKEN }}
